name: release

on:
  push:
    branches:
      - main

permissions:
  checks: write
  statuses: write
  contents: write
  packages: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
    - name: release please
      uses: google-github-actions/release-please-action@v4
      id: release
      with:
        include-component-in-tag: true

    - name: get release branch name
      id: get_branch_name
      if: ${{ steps.release.outputs.prs_created == 'true' }}
      run: |
        echo "branchName=$(echo $PR_METADATA | jq --raw-output '.headBranchName')" >> "$GITHUB_OUTPUT"
      env:
        PR_METADATA: ${{ steps.release.outputs.pr }}

    - name: clone repo
      uses: actions/checkout@v4
      with:
        ref: ${{ steps.get_branch_name.outputs.branchName }}

    - name: edit file
      if: ${{ steps.release.outputs.prs_created == 'true' }}
      run: |
        echo "hello" >> README.md

    - name: commit new file
      if: ${{ steps.release.outputs.prs_created == 'true' }}
      run: |
        GIT_OID=$(git rev-parse HEAD)
        FILE_CHANGES=$(git status --porcelain | awk 'match($1, "M"){pinrt $2}')
        FILE_ADDITIONS=""
        for FILE in $FILE_CHANGES; do
          FILE_BASE64=$(base64 -w 0 $FILE)
          FILE_ADDITIONS+="{path: \"$FILE\", contents: \"$FILE_BASE64\"},"
        done
        echo $FILE_ADDITIONS
        gh api graphql -F branchName=$BRANCH -F expectedHeadOid=$GIT_OID -F files=$FILE_ADDITIONS -f query='
          mutation (
              $branchName: String!, 
              $expectedHeadOid: GitObjectID!
              $files: [FileAddition!]!
            ) { 
            createCommitOnBranch(
              input: {
                branch:
                {
                  repositoryNameWithOwner: "0xdbe/turborepo-test",
                  branchName: $branchName
                },
                message: {headline: "chore(test): commit message"},
                fileChanges: {
                  additions: $files
                }
                expectedHeadOid: $expectedHeadOid
              }
            ){
              commit {
                url
              }
            }
          }'
      env:
        GH_TOKEN: ${{ github.token }}
        BRANCH: ${{ steps.get_branch_name.outputs.branchName }}

    - name: print released packages
      run: echo ${{ steps.release.outputs.paths_released }}
    - name: clone repository
      uses: actions/checkout@v4
      if: ${{ steps.release.outputs.releases_created == 'true' }}
    - name: configure npm
      uses: actions/setup-node@v4
      with:
        node-version: 20
        registry-url: 'https://npm.pkg.github.com'
        scope: '@0xdbe'
        always-auth: true
      env:
        NODE_AUTH_TOKEN: ${{ github.token }}
      if: ${{ steps.release.outputs.releases_created == 'true' }}
    - name: install yarn
      run: npm install -g yarn
      if: ${{ steps.release.outputs.releases_created == 'true' }}
    - name: install dependencies
      run: yarn install
      if: ${{ steps.release.outputs.releases_created == 'true' }}
    - name: Build
      run: yarn build
      if: ${{ steps.release.outputs.releases_created == 'true' }}
    - name: Publish '@0xdbe/docs' apps
      run: yarn workspace @0xdbe/docs publish
      if: ${{ steps.release.outputs['apps/docs--release_created'] == 'true' }}
    - name: Publish '@0xdbe/web' apps
      run: yarn workspace @0xdbe/web publish
      if: ${{ steps.release.outputs['apps/web--release_created'] == 'true' }}
    - name: Publish '@0xdbe/eslint-config' package
      run: yarn workspace @0xdbe/eslint-config publish
      if: ${{ steps.release.outputs['packages/eslint-config--release_created'] == 'true' }}
    - name: Publish '@0xdbe/typescript-config' package
      run: yarn workspace @0xdbe/typescript-config publish
      if: ${{ steps.release.outputs['packages/typescript-config--release_created'] == 'true' }} 
    - name: Publish '@0xdbe/ui' package
      run: yarn workspace @0xdbe/ui publish
      if: ${{ steps.release.outputs['packages/ui--release_created'] == 'true' }} 
