name: release

on:
  push:
    branches:
      - main

permissions:
  checks: write
  statuses: write
  contents: write
  packages: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
    - name: release please
      uses: google-github-actions/release-please-action@v4
      id: release
      with:
        include-component-in-tag: true
    - name: clone repository
      uses: actions/checkout@v4
      if: ${{ steps.release.outputs.releases_created }}
    - name: configure npm
      uses: actions/setup-node@v4
      with:
        node-version: 20
        registry-url: 'https://npm.pkg.github.com'
        scope: '@0xdbe'
        always-auth: true
      if: ${{ steps.release.outputs.releses_created }}
    - name: install yarn
      run: npm install -g yarn
      if: ${{ steps.release.outputs.releses_created }}
    - name: Build UI
      run: yarn build
      working-directory: packages/ui
      if: ${{ steps.release.outputs.packages-ui--release_created }} 
