name: release

on:
  push:
    branches:
      - main

permissions:
  checks: write
  statuses: write
  contents: write
  packages: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
    - name: release please
      uses: google-github-actions/release-please-action@v4
      id: release
      with:
        include-component-in-tag: true
    - name: print released packages
      run: echo ${{ steps.release.outputs.paths_released }}
    - name: clone repository
      uses: actions/checkout@v4
      if: ${{ steps.release.outputs.releases_created == 'true' }}
    - name: configure npm
      uses: actions/setup-node@v4
      with:
        node-version: 20
        registry-url: 'https://npm.pkg.github.com'
        scope: '@0xdbe'
        always-auth: true
      if: ${{ steps.release.outputs.releases_created == 'true' }}
    - name: install yarn
      run: npm install -g yarn
      if: ${{ steps.release.outputs.releases_created == 'true' }}
    - name: install dependencies
      run: yarn install
      if: ${{ steps.release.outputs.releases_created == 'true' }}
    - name: Build
      run: yarn build
      if: ${{ steps.release.outputs.releases_created == 'true' }}
    - name: Publish '@0xdbe/docs' apps
      run: yarn workspace @0xdbe/docs publish
      if: ${{ steps.release.outputs['apps/docs--release_created'] == 'true' }}
    - name: Publish 'web' apps
      run: yarn workspace web publish
      if: ${{ steps.release.outputs['packagappses/web--release_created'] == 'true' }}
    - name: Publish '@repo/eslint-config' package
      run: yarn workspace @repo/eslint-config publish
      if: ${{ steps.release.outputs['packages/eslint-config--release_created'] == 'true' }}
    - name: Publish '@repo/typescript-config' package
      run: yarn workspace @repo/typescript-config publish
      if: ${{ steps.release.outputs['packages/typescript-config--release_created'] == 'true' }} 
    - name: Publish '@repo/ui' package
      run: yarn workspace @repo/ui publish
      if: ${{ steps.release.outputs['packages/ui--release_created'] == 'true' }} 

      
