name: release

on:
  push:
    branches:
      - main

permissions:
  checks: write
  statuses: write
  contents: write
  packages: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
    - name: release please
      uses: google-github-actions/release-please-action@v4
      id: release
      with:
        include-component-in-tag: true
    - name: debug PR data
      if: ${{ steps.release.outputs.prs_created == 'true' }}
      run: echo ${{ steps.release.outputs.pr }}
    - name: commit new file
      if: ${{ steps.release.outputs.prs_created == 'true' }}
      run: |
        gh api graphql -F query='
          mutation { 
            createCommitOnBranch(
              input: {
                branch:
                {
                  repositoryNameWithOwner: "0xdbe/turborepo-test",
                  branchName: ${{ steps.release.outputs.pr.headBranchName }}
                },
                message: {headline: "chore(test): commit message"},
                fileChanges: {
                  additions: {path: "hello.md", contents: "aGVsbG8="}
                }
                expectedHeadOid: ${{ steps.release.outputs.pr.sha }}
              }
            )
          }'
      env:
        GH_TOKEN: ${{ github.token }}

    - name: print released packages
      run: echo ${{ steps.release.outputs.paths_released }}
    - name: clone repository
      uses: actions/checkout@v4
      if: ${{ steps.release.outputs.releases_created == 'true' }}
    - name: configure npm
      uses: actions/setup-node@v4
      with:
        node-version: 20
        registry-url: 'https://npm.pkg.github.com'
        scope: '@0xdbe'
        always-auth: true
      env:
        NODE_AUTH_TOKEN: ${{ github.token }}
      if: ${{ steps.release.outputs.releases_created == 'true' }}
    - name: install yarn
      run: npm install -g yarn
      if: ${{ steps.release.outputs.releases_created == 'true' }}
    - name: install dependencies
      run: yarn install
      if: ${{ steps.release.outputs.releases_created == 'true' }}
    - name: Build
      run: yarn build
      if: ${{ steps.release.outputs.releases_created == 'true' }}
    - name: Publish '@0xdbe/docs' apps
      run: yarn workspace @0xdbe/docs publish
      if: ${{ steps.release.outputs['apps/docs--release_created'] == 'true' }}
    - name: Publish '@0xdbe/web' apps
      run: yarn workspace @0xdbe/web publish
      if: ${{ steps.release.outputs['apps/web--release_created'] == 'true' }}
    - name: Publish '@0xdbe/eslint-config' package
      run: yarn workspace @0xdbe/eslint-config publish
      if: ${{ steps.release.outputs['packages/eslint-config--release_created'] == 'true' }}
    - name: Publish '@0xdbe/typescript-config' package
      run: yarn workspace @0xdbe/typescript-config publish
      if: ${{ steps.release.outputs['packages/typescript-config--release_created'] == 'true' }} 
    - name: Publish '@0xdbe/ui' package
      run: yarn workspace @0xdbe/ui publish
      if: ${{ steps.release.outputs['packages/ui--release_created'] == 'true' }} 
